### PR TITLE
Automatically push to refs/for/master

### PR DESCRIPTION
**Pull request by vog**
Configure Git to always push to refs/for/master, so pushing to
Gerrit can be done by a plain "git push".

### CODE REVIEW

**Comment by jokumer** [comment]
There are further matches, where `HEAD:refs/for/master` are documented. Should these adopted too?

**Comment by sypets** [comment]
Yes, I think it would be a good idea if this is consistent. 

* Git setup: https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Setup/Git/Index.html
* Git cheat sheet: https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/CheatSheets/Git.html

**Comment by sypets** [comment]
@vog You can add the other changes to your PR yourself or someone else can do it. Just let us know. Thanks.

**Comment by vog** [comment]
I'd prefer if somebody else would do that.

**Comment by sypets** [comment]
Ok. I can do it. Thanks for your initiative.

**Comment by jonaseberle** [comment]
Thank you both!

**Pull request merged**
