### PR TITLE
added windows troubleshooting page

### PR DESCRIPTION
**Pull request by n3amil**
Hi, i just added a troubleshooting page for windows where i started writing down about the issues we had on the codesprint in dresden with windows + ssh + git

### CODE REVIEW

**Comment by sypets** [comment]
@n3amil Thanks for doing this! 

I don't use Windows so I can't really verify this. I will give it a quick going over and merge it shortly, though. If you can ask some more people to verify it, that would be very helpful. 

Some additional hints about formatting etc.:

* make sure the underlines of your headers are at least as long as the text, see https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/HeadlinesAndSection.html#length-of-underlines
* make sure you always indent consistently (3 spaces per indenting level), see https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/CodingGuidelines.html#whitespace-and-indenting

See also this for some common errors : https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/CommonPitfalls.html

Don't worry too much about the formatting. That's usually the least work to fix. However, if you can  render locally, please do so before you create your pull request (I noticed you are also working on a PR to improve the information for Windows concerning the docker container. Thanks for doing that too!). 

The basic reST stuff should be displayed correctly in the Github preview though.

**Comment by n3amil** [comment]
We had 3 ppl here with windows 10 having the same issues and we fixed it that way.

~About the formatting - maybe we should provide a .editorconfig to do some auto-formatting?~

- i just found this https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/CodingGuidelines.html

the link to the  .editorconfig isnt working, is there a reason why this .editorconfig is not existing in the repository root? i would expect this in every documentation in the root.

**Comment by sypets** [comment]
@n3amil Thanks for pointing this out. I will fix the link. Every documentation project should contain an .editorconfig. We have not included it in every repo though (yet), but plan to do so. You can also use the .editorconfig from the core because the configuration concerning .rst should be the same. 

If anything else comes up, there is already an open issue for unifying the files. You can check there, ask questions or comment: https://github.com/TYPO3-Documentation/T3DocTeam/issues/11

**Comment by sypets** [comment]
Your change is now rendered: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Appendix/Windows/Troubleshooting.html

**Pull request merged**
