### PR TITLE
added hint for ddev start stopped working caused by corrupted db

### PR DESCRIPTION
**Pull request by n3amil**
if you dont run "ddev stop" or "ddev remove" in your project befor restarting/shutting down docker, it might corrupt your database.

this causes ddev start to stop working, you have to remove the  database & data entirely.  
This happens on windows quite often and might appear for mac users aswell. 
For more info see the linked issue from ddev

### CODE REVIEW

**Comment by sypets** [comment]
Thanks for the PR. 

It might make sense to clarify it a bit more when you should use `ddev stop` and when `ddev remove`: In the instructions, it recommends to use `ddev remove` to shtudown, but you refer to `ddev stop` (" dont run "ddev stop" before in currently running ddev").

**Comment by n3amil** [comment]
It seems like i should describe this more detailed. 

The problem:
- you run ddev start and its fails with the described error Message

This happens because:
-the Database ist corrupt

Why is the Database corrupt?
- the user shutdown/restarted Docker , without running "ddev stop" or "ddev remove" before, inside the project
- the currently running containers (incl. database container) crash and are not shutdown properly

**Comment by n3amil** [comment]
So its Important to run one of both ("ddev stop"" or "ddev remove") commands before stopping the docker (manually restarting docker, or by PC restart/shutdown etc.).

**Comment by n3amil** [comment]
i just made a pull request, with a small change which should clearify that

**Pull request merged**
