### PR TITLE
[TASK] Document signature algorithm SSH problem

### PR DESCRIPTION
**Pull request by astehlik**

### CODE REVIEW

**Comment by astehlik** [comment]
Maybe someone from the server team can confirm that this is a valid solution ;)

At least it solved my problem (using Fedora 33) when trying to push to Gerrit.

**Comment by flicstar** [comment]
I reached out to the Server Team to get a review.

**Comment by flicstar** [comment]
See chat in Slack: https://typo3.slack.com/archives/C041L7V6Q/p1622326566011300

> Alexander Stehlik : Do you think it makes sense to add this to the invalid key format section?

> Stephan Großberndt:ghost: Yes, if the default format by ssh-keygen is not accepted by Gerrit, we should add a hint in the documentation. Maybe add a link to https://review.typo3.org/Documentation/config-gerrit.html#sshd.kex too.

**Review by linawolf — APPROVED** [review]

**Comment by astehlik** [comment]
Sorry, @linawolf, I think there was a misunderstanding.

The documented solution in the merge request was unfortunately not the one that should end up in the documentation.

Can you please revert the changes and I will create a new pull request with the preferred solution of Stephan.

Thank you :)

**Pull request merged**
