### PR TITLE
Change order for composer install

### PR DESCRIPTION
**Pull request by sypets**
The command "composer install" (via runTests.sh) should be called before "first install".

### CODE REVIEW

**Comment by linawolf** [comment]
On a ddev system you need to do ddev start so you have the PHP version etc to do a ddev composer install...

**Comment by sypets** [comment]
> On a ddev system you need to do ddev start so you have the PHP version etc to do a ddev composer install...

You are right. However that is only true for running in DDEV context (which is not really recommended anyway, runTests.sh should be used).  But since we offer both commands, this should work. I changed the order again slightly. I separate "ddev start" (which can be run first) from launching the URL in the browser.

I would like to make sure composer install was run before trying to access the site in the browser, because otherwise not all files will be available (e.g. install.php which is not in the git repo).

**Comment by linawolf** [comment]
We are in the file "[SettingUpTypo3Ddev.rst](https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/309/files#diff-1029f04bbf4467cd11588ddd9f68e3c9b8d791cae43cba096c9deedcda05751a)" so the complete chapter is about using ddev for setup

**Comment by sypets** [comment]
Is is about setting up an installation with DDEV. The "composer install" however can be done with runTests.sh, regardless of how the site was setup in. In fact, most of the setup calls can now be done with runTests.sh, and I think this is the recommended method. 

I am closing now.

**Pull request closed without merging**
