### PR TITLE
Commit Message line length is 72 characters

### PR DESCRIPTION
**Pull request by rr-it**
See step 3 in https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/BugfixingAZ/Index.html#fix-the-code

And also Gerrit code base - CSS:
```css
.commitMessage {
  max-width: calc(72ch + 2px + 2 * var(--spacing-m) + 0.4px);
}
```

### CODE REVIEW

**Comment by garvinhicking** [comment]
This limit stems from:

https://github.com/TYPO3/typo3/blob/main/Build/git-hooks/commit-msg#L197

The "72" character limit is more common when googline for it. If we change this though, we should IMO sync this up with the core first, mentioned on slack too:

https://typo3.slack.com/archives/C03AM9R17/p1710168074140009

**Comment by garvinhicking** [comment]
Hm, we already refer to 72 here:

https://docs.typo3.org/m/typo3/guide-contributionworkflow/draft/en-us/Appendix/CommitMessage.html#commitmessage

and here:

https://docs.typo3.org/m/typo3/guide-contributionworkflow/draft/en-us/BugfixingAZ/Index.html

That "74" is the only place left, which this PR addresses. However, "74" is actually the number that the githook of the core references. Aargh :D

**Comment by garvinhicking** [comment]
I would wait for the core merge to go through, then merge this, ok?

**Comment by brotkrueml** [comment]
Yup, that's why I haven't merged it yet.

**Comment by garvinhicking** [comment]
Mergef after core patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83406

**Pull request merged**
