### PR TITLE
Clarify git push to gerrit

### PR DESCRIPTION
**Pull request by christophlehmann**

### CODE REVIEW

**Comment by sypets** [comment]
Could you explain this a little?

I found https://stackoverflow.com/questions/10461214/why-is-git-push-gerrit-headrefs-for-master-used-instead-of-git-push-origin-mast

Shouldn't the standard command for pushing be changed as well?

Currently, it is:

`git push origin HEAD:refs/publish/master`

see https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/BugfixingAZ/Index.html#pushing-your-changes

If you always do it - as it is currently documented - your change has no effect, right?

**Comment by christophlehmann** [comment]
Hey sypets, didn't know the url https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/BugfixingAZ/Index.html#pushing-your-changes which explains it very good and we can close this one here. 

But can you please put a link in `Documentation/Setup/Git/Index.rst` to your BugfixingAZ/Index.html since the question how to push was not one of the firsts google hits. Thanks :-)

**Comment by sypets** [comment]
@christophlehmann Actually, I still think your change is a good idea. It's better to set the default than to have to specify the refs on every push, right? 

For this, it might be a good idea to move the discussion to the coredev channel. I'll leave this PR open a little while longer.

About the link you suggested. I can do that, but I think we need to put some more work into "Fixing a bug A-Z" and generally structure the guide so it's easier to find things. "Fixing a bug A-Z" has not been restructured, new things have just been added (documentation and testing), so now there is too much information in that chapter and what you usually need (the push command) is way on the bottom. 

I already added the cheat sheet for git (see https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/CheatSheets/Git.html). You might find this helpful in the future. 

I also added the quicklinks (buttons on the top) on the startpage: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Index.html

Problem is: it's a lot of information and not everyone (or probably noone) will read the guide entirely. So landing on the correct page via Google is crucial. I'll see if I can add a few more links in general.

If you have any other ideas for how to structure or improve findability, feel free to open a new issue or PR here! Also, if you want to add things to the cheat sheet, that would be welcome.

**Comment by sypets** [comment]
Some links were added to the section. Closing this for now.

**Pull request closed without merging**
