### PR TITLE
Fix invalid links to Forger

### PR DESCRIPTION
**Pull request by mbrodala**
It must be forger.typo3.COM, not forger.typo3.ORG

### CODE REVIEW

**Comment by gilbertsoft** [comment]
@mbrodala you also have to fix https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/blob/master/Documentation/Includes.txt

**Review by gilbertsoft — CHANGES_REQUESTED** [review]
You also have to fix https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/blob/master/Documentation/Includes.txt

**Comment by mbrodala** [comment]
@gilbertsoft Already noticed and fixed everything. It would be better to have the base URL in a single location but that'll too be hassle for now.

**Comment by gilbertsoft** [comment]
> 
> 
> @gilbertsoft Already noticed and fixed everything. It would be better to have the base URL in a single location but that'll too be hassle for now.

Yeah, thought the same. But not sure if this is possible at all with the URI sub parts used on some locations.

**Review by gilbertsoft — APPROVED** [review]

**Comment by mbrodala** [comment]
I also updated this in all other doc repositories and linked these changes here.

@DanielSiepmann Should https://github.com/TYPO3-Documentation/WIP-Algolia-Docsearch-Integration be updated, too?

**Pull request merged**
