### PR TITLE
Fix article in Index.rst

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Review by linawolf — APPROVED** [review]

**Comment by linawolf** [comment]
Congratulations for your first contribution!

**Comment by stweil** [comment]
Unrelated: I just noticed that https://openhub.net/p/typo3documentation does not show the relevant information because of missing or wrong settings for the code locations. This can only be fixed by @fsuter (unless he releases the project maintenance to everybody).

**Comment by fsuter** [comment]
Oh my, that does ring a very old and dusty bell at a great distance... The good news is that I could login again and I'm indeed the project's manager, and totally willing to hand it over. I didn't see how I could "release the project maintenance to everybody", so if you have a pointer I'll gladly do it. Otherwise what I found is that people can apply as managers. I can then validate these people and remove myself.

**Comment by stweil** [comment]
It's sufficient to remove yourself as a manager. Many other projects don't have one, and usually this works fine.

**Comment by fsuter** [comment]
OK. Done: https://openhub.net/p/typo3documentation/managers

**Pull request merged**
